name: "Supabase Koruma Kalkanı (Tasarruf Modu)"

on:
  schedule:
    # Her 12 saatte bir çalışır (Günde sadece 2 kez sistemi dürter)
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  ping_sunucu:
    runs-on: ubuntu-latest
    steps:
      - name: "Sıraç Aksan Nöbet Sistemine İstek Gönderiliyor"
        run: |
          curl -I -s https://sirac-aksan-nobet-program.onrender.com
          echo "Sistem başarıyla dürtüldü, Supabase donmaktan kurtarıldı!"
